[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000_000
# via_ir = true

fs_permissions = [
  { access = "read", path = "broadcast/"},
  { access = "read-write", path = ".records/"},
  { access = "write", path = "./seatbelt-example.json"}
]

[lint]
exclude_lints = [
  "mixed-case-function",
  "mixed-case-variable",
  "pascal-case-struct",
  "screaming-snake-case-const"
]

[fmt]
line_length = 100
tab_width = 4
style = "space"
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
hex_underscore = "preserve"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
docs_style = "line"
contract_new_lines = false
sort_imports = true
namespace_import_style = "prefer_plain"
pow_no_space = false
prefer_compact = "all"
single_line_imports = false
